### ISSUE TITLE
在线运行代码输入出现bug

### ISSUE THREAD

**Issue by Kirityou7** [MingxuanGame/zhenxun_plugin_code#1]
[[](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/issues/49)](https://github.com/zhenxun-org/nonebot_plugins_zhenxun_bot/issues/49#issuecomment-1135406121)
如这篇issue，我也不知道会不会引起其他bug，是按照@yzyyz大佬的源代码进行了修改（py小白大部分都看不懂捏QWQ）

**Comment by MingxuanGame** [comment]
谢谢发现此问题，已于 https://github.com/MingxuanGame/zhenxun_plugin_code/commit/1cfe0a4dbe46d172a1a7e03c4aa0684702a5dffb 修复
